### ISSUE TITLE
Vertical alignment of overview and contents buffer

### ISSUE THREAD

**Issue by suvayu** [knupfer/org-panes#1]
The overview and contents buffer are always in the middle of the buffer vertically.  I would expect it to have been at the top of the buffer like normal Emacs buffers.  I have attached a screenshot to show what I'm saying.  Can this be addressed?

![org-panes](https://cloud.githubusercontent.com/assets/229540/4023558/d1ad5df6-2b98-11e4-8f26-899de9eeb87c.png)

This looks like a great library, I think I will use it when I'm working on large screens.  Thank you!

**Comment by knupfer** [comment]
Dear suvayu, thank you for your feedback. I've added a option to choose between horizontal and vertical split, but only concerning the overview and the contents buffer. I hope that this is what you meant. Splitting all windows horizontally would not be very wise concerning the free space on a screen. Looking at your screenshot, I suggest, that you customize a bit the colors according to your theme, for example, normally the visible part of the show all buffer is highlighted in the other two buffers.

![2014-08-24-174331_2560x1600_scrot](https://cloud.githubusercontent.com/assets/5609565/4023817/2bdf5518-2ba8-11e4-87ae-54e3a9779e15.png)
![2014-08-24-174429_2560x1600_scrot](https://cloud.githubusercontent.com/assets/5609565/4023818/2be346b4-2ba8-11e4-9776-ddcbc1c46e88.png)

May I ask you if you've got ideas to improve the code? I'm new to programming (i'm a musician) and appreciate help very much.
Greets

**Comment by brabalan** [comment]
I think that suvayu meant that the text should be at the top, and not in the middle, of the OVERVIEW and CONTENTS buffers.

**Comment by suvayu** [comment]
Sorry for the delayed response.  @brabalan is right, I meant the overview and contents buffer should be aligned at the top, as in, if it is small the white space is below the text not above it.  That said, I think the feature you added could be useful for smaller screens.  Now I might consider using it even on my tiny thinkpad! :)

**Comment by knupfer** [comment]
oh, ok. I thought, that this is a feature which gives some clarity. I added a option in customize to opt-out the centering of the text. Further changed a lot of other stuff (now the panes restore themselfs if switched back to the buffer (this is customizable)) and improved the performance by roughly a factor of 100 (the overlays are now only redrawn, when the visible headings in the show all buffer significantly change, and not after every command).
