### ISSUE TITLE
org-panes creates 5 windows instead of 3

### ISSUE THREAD

**Issue by brabalan** [knupfer/org-panes#2]
Something must be interfering with org-pane because when I call it in a frame with a single window, I get this

![screen shot 2014-08-27 at 09 02 05](https://cloud.githubusercontent.com/assets/1021637/4056305/8a69ac98-2db8-11e4-9a01-0beb18ce2a42.png)

**Comment by brabalan** [comment]
I tried debugging to see what is going on, and the problem is the call to `clone-indirect-buffer` in `org-panes-establish-layout` which splits the window horizontally. I looked at the documentation of that function and I have no idea why it does that.

**Comment by knupfer** [comment]
I think that I've found what's causing the issue. I used the display-flag from clone-indirect-buffer to clone it in the beforehand splitted, other window. But the display-flag calls pop-to-buffer which is a bit blurry and might behave different on different window sizes. I've made selecting and cloning more explicit, would you please report if it works now for you?
Greets

**Comment by brabalan** [comment]
It's working great now, thanks.

**Comment by knupfer** [comment]
wonderful! if you've got further suggestions don't hestitate, I like to learn
