### ISSUE TITLE
org-panes and switching to workgroups2

### ISSUE THREAD

**Issue by brabalan** [knupfer/org-panes#3]
I use workgroups2 (https://github.com/pashinin/workgroups2) and I've noticed that when I switch from an org-pane enabled frame to another workgroup, the layout of the target workgroup is changed to become a single window. For instance, if it was a vertically split window, I see the split go away.

**Comment by knupfer** [comment]
I made the window-killing a bit more sensible, perhaps it's fixed by that. I'm not using workgroups, so let me know if there remains an issue.

**Comment by brabalan** [comment]
Yes, it seems to be fixed. Thanks a lot!
